services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5572:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  model-preload:
    image: ghcr.io/itmo-monitoring-system/face-recognizing:latest
    environment:
      FACE_ANALYSIS_CTX_ID: "-1"
      FACE_ANALYSIS_DET_SIZE: "640"
      NO_ALBUMENTATIONS_UPDATE: "1"
    working_dir: /app
    volumes:
      - /home/deploy/insightface:/root/.insightface
    entrypoint: ["/bin/sh","-lc"]
    command: >
      python -c "import os;
      from insightface.app import FaceAnalysis;
      app=FaceAnalysis(allowed_modules=['detection','recognition']);
      det_size=int(os.getenv('FACE_ANALYSIS_DET_SIZE', '640'));
      ctx_id=int(os.getenv('FACE_ANALYSIS_CTX_ID', '-1'));
      app.prepare(ctx_id=ctx_id, det_size=(det_size, det_size));
      print('model ready')"

  face-service:
    image: ghcr.io/itmo-monitoring-system/face-recognizing:latest
    depends_on:
      - rabbitmq
      - redis
      - model-preload
    ports:
      - "8180:8180"
    environment:
      FACE_RECOGNITION_THRESHOLD: "0.55"
      FACE_ANALYSIS_CTX_ID: "-1"
      FACE_ANALYSIS_DET_SIZE: "640"
      OUT_AMQP_URL: amqp://user:pass@rabbitmq:5672/
      OUT_QUEUE_PREFIX: faces.recognition.out

      BACKEND_URL: https://projctviscon.vps.webdock.cloud
      BACKEND_START_PATH: /api/service/lecture/start
      BACKEND_STOP_PATH: /api/service/lecture/stop

      BACKEND_DATASET_PATH: /api/service/dataset

      REDIS_URL: redis://redis:6379/0
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app
      NO_ALBUMENTATIONS_UPDATE: "1"
    command: [ "python", "-m", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8180", "--log-level", "debug" ]
    volumes:
      - /home/deploy/insightface:/root/.insightface
    working_dir: /app
