services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5572:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  face-service:
    image: ghcr.io/itmo-monitoring-system/face-recognizing:latest
    depends_on:
      - rabbitmq
      - redis
    ports:
      - "8180:8180"
    environment:
      REDIS_URL: redis://redis:6379/0
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: user
      RABBIT_PASS: pass
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app
    command: [ "python", "-m", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8180", "--log-level", "debug" ]
    volumes:
      - ${INSIGHTFACE_MODELS}:/root/.insightface
    working_dir: /app
